# Whiteflag API configuration file
#
# This configuration file provides global configuration parameters for the api.
# Please see `./docs/configuration.md` for a description.
#

[logger]
loglevel = 5

[server]
protocol = "http"
hostname = ""
port = "5746"

[authorization]
username = ""
password = ""

[ssl]
keyFile = ""
certificateFile = ""

[http]
enableCors = false
trustProxy = false

[socket]
enable = true

[endpoints]
sendMessage = true
receiveMessage = true
transferValue = true
createAccount = true
updateAccount = true
deleteAccount = true
createSignature = true
updateOriginator = true
deleteOriginator = true
storePreSharedKey = true
deletePreSharedKey = true
storeAuthToken = true
deleteAuthToken = true
