# Whiteflag blockchains configuration file
#
# This configuration file contains blockchain related configuration parameters
# Please see `./docs/configuration.md` for a description.
#

[confirmation]
enabled = true
interval = 6000
maxBlockDepth = 8
updateEachBlock = false

[[blockchains]]
name = "ethereum-rinkeby"
module = "ethereum"
chainID = 4 # Rinkeby
active = false
createAccount = false
blockRetrievalInterval = 6000
blockRetrievalStart = 0
blockRetrievalEnd = 0
blockRetrievalRestart = 100
blockMaxRetries = 0
transactionBatchSize = 64
transactionValue = "0"
traceRawTransaction = false
rpcProtocol = "https"
rpcHost = "https://rinkeby.infura.io/v3/a40f9cbe88ee4758ab51b0682175e7b8"
rpcPort = "443"
rpcPath = ""
username = ""
password = ""

[[blockchains]]
name = "topl-testnet"
module = "bifrost"
chainID = 0 # Testnet
active = false
createAccount = false
blockRetrievalInterval = 6000
blockRetrievalStart = 0
blockRetrievalEnd = 0
blockRetrievalRestart = 100
blockMaxRetries = 0
transactionBatchSize = 64
transactionValue = "0"
traceRawTransaction = false
rpcProtocol = "http"
rpcHost = "localhost"
rpcPort = "9085"
rpcPath = ""
username = ""
password = ""